# SUMMER SCHOOL PRACTICE

In [25]:
# Initialize Otter
import otter
grader = otter.Notebook("DSA2024Test.ipynb")

In [21]:
import pandas as pd
import numpy as np
%matplotlib inline
import otter

grader = otter.Notebook()

In [22]:
def isValid(s: str) -> bool:
    stack = []
    mapping = {')': '(', '}': '{', ']': '['}

    for char in s:
        if char in mapping.values():
            stack.append(char)
        elif char in mapping.keys():
            if not stack or mapping[char] != stack.pop():
                return False
        else:
            return False
    return len(stack) == 0


In [26]:
grader.check("q1")

q1 results: All test cases passed!

In [27]:
def oddFrequencyCounter(theParagraph):
    # Create a dictionary to store character frequencies
    char_freq = {}
    
    # Count frequencies of characters in the paragraph
    for char in theParagraph:
        if char in char_freq:
            char_freq[char] += 1
        else:
            char_freq[char] = 1
    
    # Count the number of characters with odd frequencies
    odd_count = 0
    for freq in char_freq.values():
        if freq % 2 != 0:  # If frequency is odd
            odd_count += 1
    
    return odd_count

# Test the function
theParagraph = "I am a child of God. God is my Father."
result = oddFrequencyCounter(theParagraph)
print("Number of characters with odd frequencies:", result)  


Number of characters with odd frequencies: 14


In [28]:
grader.check("q2")

q2 results: All test cases passed!

In [52]:
def odd_squares(limit):
    odd = 1
    for _ in range(limit):
        yield odd * odd
        odd += 2

# Create the generator for the first 6 odd squares
theGen = odd_squares(6)

# Print the squares of the first 6 odd numbers
for square in theGen:
    print(square)


1
9
25
49
81
121


In [53]:
grader.check("q3")

q3 results: All test cases passed!

In [35]:
def odd_squares_sum(limit):
    num = 1
    while num <= limit:
        yield num * num
        num += 2  # Move to the next odd number

# Create the generator
theGen = odd_squares_sum(20)

# Create an empty list to store the squares
result_list = []

# Generate the squares and store in the list
for _ in range(10):  # We want 11 elements to include squares up to 20
    result_list.append(next(theGen))

# Convert the list to a NumPy array
oddSumList = np.array(result_list)

print(oddSumList)


[  1   9  25  49  81 121 169 225 289 361]


In [36]:
grader.check("q4")

q4 results: All test cases passed!

In [37]:
import numpy as np

def odd_squares_sum(limit):
    num = 1
    while num <= limit:
        yield num * num
        num += 2  # Move to the next odd number

# Create the generator
theGen = odd_squares_sum(20)

# Create an empty list to store the squares
result_list = []

# Generate the squares and store in the list
for _ in range(10):  # We want 10 elements to include squares up to 20
    result_list.append(next(theGen))

# Convert the list to a NumPy array
oddSumList = np.array(result_list)

# Compute element-wise remainder of oddSumList when divided by 5
remainder_list = oddSumList % 5

# Merge oddSumList with remainder_list into a list of tuples
mergedList = list(zip(remainder_list, oddSumList))

print(mergedList)


[(1, 1), (4, 9), (0, 25), (4, 49), (1, 81), (1, 121), (4, 169), (0, 225), (4, 289), (1, 361)]


In [38]:
grader.check("q5")

q5 results: All test cases passed!

In [40]:
def greatest_common_divisor(a, b):
    while b != 0:
        a, b = b, a % b
    return a

# Test the function
print(greatest_common_divisor(35, 63))  # Output: 5



7


In [41]:
grader.check("q6")

q6 results: All test cases passed!

In [42]:
def l1_distance(pt1, pt2):
   
    return np.sum(np.abs(pt1 - pt2))

def get_3_nearest(pt, ptlist):
     # Calculate distances to all points in the list
    distances = [l1_distance(pt, np.array(p)) for p in ptlist]

    # Sort the points based on distances
    sorted_indices = np.argsort(distances)

    # Get the 3 nearest points and sort them by distance
    nearest_points = [ptlist[i] for i in sorted_indices[:3]]
    nearest_points.sort(key=lambda x: l1_distance(pt, np.array(x)))

    return nearest_points

# Test the function
pt = np.array([0, 0])
ptlist = [
    [1, 1],
    [-1, 2],
    [2, -1],
    [3, 3],
    [-2, 0],
]

nearest = get_3_nearest(pt, ptlist)
print("3 Nearest Points to [0, 0]:")
for p in nearest:
    print(p)

# Additional test case
nearest_additional = get_3_nearest((5, 8), [(5, 9), (9, 1), (2, 4), (13, 9), (10, 12)])
print("\n3 Nearest Points to [5, 8]:")
for p in nearest_additional:
    print(p)

3 Nearest Points to [0, 0]:
[1, 1]
[-2, 0]
[-1, 2]

3 Nearest Points to [5, 8]:
(5, 9)
(2, 4)
(13, 9)


In [43]:
grader.check("q7")


q7 results: All test cases passed!

In [44]:
def diagonal_vector(M):
    diagonal_entries = np.diagonal(M)
    absolute_diagonal = np.absolute(diagonal_entries)
    
    return absolute_diagonal

# Test the function
M = np.array([[1, 2, 3],
              [4, -5, 6],
              [7, 8, -9]])

result = diagonal_vector(M)
print(result)  # Output: [1 5 9]

[1 5 9]


In [45]:
grader.check("q8")

q8 results: All test cases passed!

In [47]:
def flatten_reverse_lists(superlist):
    flattened_list = [item for sublist in superlist for item in sublist]
    sorted_list = sorted(flattened_list, key=lambda x: x, reverse=True)
    
    return sorted_list

# Test the function
result = flatten_reverse_lists([[2, 13, 44], [6, 7]])
print(result)  #


[44, 13, 7, 6, 2]


In [48]:
grader.check("q9")

q9 results: All test cases passed!

In [49]:
# Define the data
data = {
    'flavor': ['white chocolate', 'vanilla', 'dark chocolate', 'strawberry', 'strawberry', 
               'vanilla', 'mint', 'mint', 'white chocolate', 'dark chocolate', 
               'white chocolate', 'dark chocolate'],
    'scoops': [1, 1, 2, 1, 3, 2, 1, 2, 3, 3, 2, 5],
    'price': [2, 1.5, 3, 2, 4, 2, 4, 5, 2, 3, 2, 3]
}

# Create the DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
df

flavor  scoops  price
0   white chocolate       1    2.0
1           vanilla       1    1.5
2    dark chocolate       2    3.0
3        strawberry       1    2.0
4        strawberry       3    4.0
5           vanilla       2    2.0
6              mint       1    4.0
7              mint       2    5.0
8   white chocolate       3    2.0
9    dark chocolate       3    3.0
10  white chocolate       2    2.0
11   dark chocolate       5    3.0

In [63]:


# Define the data
data = {
    'flavor': ['white chocolate', 'vanilla', 'dark chocolate', 'strawberry', 'strawberry', 
               'vanilla', 'mint', 'mint', 'white chocolate', 'dark chocolate', 
               'white chocolate', 'dark chocolate'],
    'scoops': [1, 1, 2, 1, 3, 2, 1, 2, 3, 3, 2, 5],
    'price': [2, 1.5, 3, 2, 4, 2, 4, 5, 2, 3, 2, 3]
}

# Create the DataFrame
df = pd.DataFrame(data)

# Create the new column 'total_price' by multiplying 'scoops' and 'price'
df['total_price'] = df['scoops'] * df['price']

# Display the updated DataFrame
df


flavor  scoops  price  total_price
0   white chocolate       1    2.0          2.0
1           vanilla       1    1.5          1.5
2    dark chocolate       2    3.0          6.0
3        strawberry       1    2.0          2.0
4        strawberry       3    4.0         12.0
5           vanilla       2    2.0          4.0
6              mint       1    4.0          4.0
7              mint       2    5.0         10.0
8   white chocolate       3    2.0          6.0
9    dark chocolate       3    3.0          9.0
10  white chocolate       2    2.0          4.0
11   dark chocolate       5    3.0         15.0

In [50]:
import pandas as pd
import numpy as np

def groupStatistics(data, groupValue):
   
    # Convert list of dictionaries to a Pandas DataFrame
    df = pd.DataFrame(data)
    
    # Convert 'scoops' and 'price' columns to float
    df['scoops'] = df['scoops'].astype(float)
    df['price'] = df['price'].astype(float)
    
    # Create the 'total_price' column by multiplying 'scoops' and 'price'
    df['total_price'] = df['scoops'] * df['price']
    
    # Group the data by 'flavor'
    grouped_data = df.groupby('flavor')
    
    try:
        # Get the group specified by 'groupValue'
        group = grouped_data.get_group(groupValue)
        
        # Calculate the statistics
        mean = round(group['total_price'].mean(), 2)
        median = round(group['total_price'].median(), 2)
        min_val = round(group['total_price'].min(), 2)
        max_val = round(group['total_price'].max(), 2)
        std = round(group['total_price'].std(), 2)  # Round std to 2 decimal places
        
        # Create a numpy array with the statistics
        stats_array = np.array([mean, median, min_val, std])
        
        return stats_array
    except KeyError:
        print(f"Group '{groupValue}' not found.")
        return np.array([np.nan, np.nan, np.nan, np.nan])

# Test the function
data = [
    {'flavor': 'white chocolate', 'scoops': 1, 'price': 2},
    {'flavor': 'vanilla', 'scoops': 1, 'price': 1.5},
    {'flavor': 'dark chocolate', 'scoops': 2, 'price': 3},
    {'flavor': 'strawberry', 'scoops': 1, 'price': 2},
    {'flavor': 'strawberry', 'scoops': 3, 'price': 4},
    {'flavor': 'vanilla', 'scoops': 2, 'price': 2},
    {'flavor': 'mint', 'scoops': 1, 'price': 4},
    {'flavor': 'mint', 'scoops': 2, 'price': 5},
    {'flavor': 'white chocolate', 'scoops': 3, 'price': 2},
    {'flavor': 'dark chocolate', 'scoops': 3, 'price': 3},
    {'flavor': 'white chocolate', 'scoops': 2, 'price': 2},
    {'flavor': 'dark chocolate', 'scoops': 5, 'price': 3}
]

# Calculate statistics for 'white chocolate'
stats_white_choc = groupStatistics(data, 'white chocolate')
print("Statistics for 'white chocolate':")
print(stats_white_choc)

# Calculate statistics for 'vanilla'
stats_vanilla = groupStatistics(data, 'vanilla')
print("\nStatistics for 'vanilla':")
print(stats_vanilla)

# Calculate statistics for 'dark chocolate'
stats_dark_choc = groupStatistics(data, 'dark chocolate')
print("\nStatistics for 'dark chocolate':")
print(stats_dark_choc)

# Calculate statistics for 'strawberry'
stats_strawberry = groupStatistics(data, 'strawberry')
print("\nStatistics for 'strawberry':")
print(stats_strawberry)

# Calculate statistics for 'mint'
stats_mint = groupStatistics(data, 'mint')
print("\nStatistics for 'mint':")
print(stats_mint)


Statistics for 'white chocolate':
[4. 4. 2. 2.]

Statistics for 'vanilla':
[2.75 2.75 1.5  1.77]

Statistics for 'dark chocolate':
[10.    9.    6.    4.58]

Statistics for 'strawberry':
[7.   7.   2.   7.07]

Statistics for 'mint':
[7.   7.   4.   4.24]


In [51]:
grader.check("q11")

q11 results: All test cases passed!

In [54]:
# Save your notebook first, then run this cell to export your submission.
grader.export(pdf=False)